=== Flower63/Drugs/files/drugs.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:element name="Drugs">
            <xs:complexType>
                  <xs:sequence>
                        <xs:element name="Medicine" maxOccurs="unbounded" minOccurs="0">
                              <xs:complexType>
                                    <xs:sequence>
                                          <xs:element type="xs:string" name="Name"/>
                                          <xs:element type="xs:string" name="Pharm"/>
                                          <xs:element type="DrugGroup" name="DrugGroup"/>
                                          <xs:element type="Analogs" name="Analogs"/>
                                          <xs:element type="DrugVersion" name="DrugVersion"/>
                                          <xs:element type="Certificate" name="Certificate"/>
                                    </xs:sequence>
                                    <xs:attribute type="xs:byte" name="id" use="required"/>
                              </xs:complexType>
                        </xs:element>
                  </xs:sequence>
            </xs:complexType>
      </xs:element>

      <!-- Type of drug -->
      <xs:simpleType name="DrugGroup">
            <xs:restriction base="xs:string">
                  <xs:enumeration value="ANTIBIOTIC"/>
                  <xs:enumeration value="VITAMIN"/>
                  <xs:enumeration value="ANESTHETIC"/>
            </xs:restriction>
      </xs:simpleType>

      <!-- Version (form) of drug -->
      <xs:simpleType name="DrugVersion">
            <xs:restriction base="xs:string">
                  <xs:enumeration value="PILLS"/>
                  <xs:enumeration value="DROPS"/>
                  <xs:enumeration value="INJECTION"/>
            </xs:restriction>
      </xs:simpleType>

      <!-- Supporting certificate -->
      <xs:complexType name="Certificate">
            <xs:sequence>
                  <xs:element type="xs:string" name="Number"/>
                  <xs:element type="xs:string" name="IssueDate"/>
                  <xs:element type="xs:string" name="ExpirationDate"/>
                  <xs:element type="xs:string" name="OrganisationName"/>
            </xs:sequence>
      </xs:complexType>

      <!-- List of exist analogs. From 0 to 5 allowed -->
      <xs:complexType name="Analogs">
            <xs:sequence>
                  <xs:element type="xs:string" name="Analog" maxOccurs="5" minOccurs="0"/>
            </xs:sequence>
      </xs:complexType>
</xs:schema>

=== Flower63/Drugs/files/drugs.xml
<?xml version="1.0"?>
<Drugs xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
       xsi:noNamespaceSchemaLocation='drugs.xsd'>
    <Medicine id="1">
        <Name>Aspirin</Name>
        <Pharm>Darnitsa</Pharm>
        <DrugGroup>ANESTHETIC</DrugGroup>
        <Analogs>
            <Analog>Bufferin</Analog>
            <Analog>Micristin</Analog>
            <Analog>Colpharit</Analog>
        </Analogs>
        <DrugVersion>PILLS</DrugVersion>
        <Certificate>
            <Number>111222</Number>
            <IssueDate>10.11.2012</IssueDate>
            <ExpirationDate>12.12.2017</ExpirationDate>
            <OrganisationName>EPAM Pharmacology</OrganisationName>
        </Certificate>
    </Medicine>

    <Medicine id="2">
        <Name>Ascorbic acid</Name>
        <Pharm>Darnitsa</Pharm>
        <DrugGroup>VITAMIN</DrugGroup>
        <Analogs>
        </Analogs>
        <DrugVersion>PILLS</DrugVersion>
        <Certificate>
            <Number>111333</Number>
            <IssueDate>20.11.2012</IssueDate>
            <ExpirationDate>12.06.2017</ExpirationDate>
            <OrganisationName>EPAM Pharmacology</OrganisationName>
        </Certificate>
    </Medicine>

    <Medicine id="3">
        <Name>Ciprofloxacinum</Name>
        <Pharm>Darnitsa</Pharm>
        <DrugGroup>ANTIBIOTIC</DrugGroup>
        <Analogs>
            <Analog>Recipro</Analog>
            <Analog>Alcipro</Analog>
            <Analog>Ciprolet</Analog>
        </Analogs>
        <DrugVersion>INJECTION</DrugVersion>
        <Certificate>
            <Number>111444</Number>
            <IssueDate>25.07.2012</IssueDate>
            <ExpirationDate>30.12.2017</ExpirationDate>
            <OrganisationName>EPAM Pharmacology</OrganisationName>
        </Certificate>
    </Medicine>
</Drugs>
